# Generated by Django 4.2.3 on 2024-05-04 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Enter a valid slug consisting of letters, numbers, underscores, or hyphens.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
