# Generated by Django 5.0.6 on 2024-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0006_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
