# Generated by Django 5.0.6 on 2024-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0008_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(null=True)),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DataAnalysis', 'Data Analysis'), ('DataScience', 'Data Science'), ('Other', 'Other')], default='Other', max_length=20)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
